sudo: required #we are making it as docker
services:
  - docker
before_install: 
  - curl http://sdk.cloud.google.com | bash > /dev/null; #Download SDK google cloud and install it locally
  - source $HOME/google-cloud-sdk/path.bash.inc #Download SDK google cloud and install it locally
  - gcloud components update kubectl #install kubectl
  - gcloud auth activate-service-account --key-file service-account.json #setting credentials for the purpose